### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tomasiser** [tomasiser/pepr3d#112]
**BOLD** means **DONE**.

Structure: 

#### I. Introduction
* [x] **Introduction** - _copy pasted from Spec_
* [x] **Related work** - _copy pasted from Spec_, expanded by Jindra's comments

#### II. Developer Documentation
* [x] **Architecture**

_in the following, elaborate on classes, what they do, how they are connected, what is ours/what is a library thing_
* [x] Geometry
   * [x] Geometry
   * [x] **Model Importer**
   * [x] **Model Exporter**
   * [x] **Font Rasterizer**
   * [x] **Color Manager**
* [x] **Commands** - check this @Fro-Z  pls
* [x] **Tools**
* [x] **User interface**
* [x] Testing
   * [x] **Unit tests**
   * [x] Manual tests - corrupted files, non polyhedron files, different files (jpg), each tool test all properties, export a cube and test the insides, test error logs.
      * [x] missing: Brush and Text Tool
      * [x] **done: everything else**
   * [x] **Continuou Integration**
* [x] **Building the project**
   * [x] **Required libraries (CGAL, Assimp, Freetype, Cereal)**
   * [x] **Cmake**

#### III. Progress of implementation
* [x] **Progress of implementation**
* [x] **Comparison to minimal requirements** - _straight forward, we met all, and almost all from advanced_
* [x] **Results** - _with photos of real 3D prints_
  * [x] needs updating with new export
* [x] **Chosen techniques critique** - _choosing CGAL/cereal/cinder, some other that didnt fit in their own chapter_
* [x] **Future work on the project** - _all that doesn't work and could, e.g. different more sophisticated export_
* [x] **Conclusion**

#### IV. User Documentation
* [x] **System requirements and Installation** - one page, easy
* [x] First run *(incl. color palette?)*
* [x] Tools:
   * [x] **TriPainter**
   * [x] **BucketPainter**
   * [x] Brush
   * [x] Text
   * [x] **AutoSeg**
   * [x] **ManuSeg**
* [x] **Import, export, .p3d format** *(incl. slicer support, photos of real examples??)*
   * [x] **Import**
   * [x] **Export**
   * [x] **.p3d**
* [x] **Aditional options and settings**

**Comment by iyedwelhezi777-source** [comment]
I believe to improving your password
